# This file was generated by GoReleaser. DO NOT EDIT.
cask "entra-emulator" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "ebf70fb2fa5c5c49293b570567e12b223058924fa71c374634c3b3716e1dc548"
      url "https://github.com/calvinchengx/entra-emulator/releases/download/v#{version}/entra-emulator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4c7de39be2db4e236368832897902ca1e3f77ce06b401e8b45ab811666f9a53"
      url "https://github.com/calvinchengx/entra-emulator/releases/download/v#{version}/entra-emulator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d544e81d797b7587aaa7f63c254d093a0b3fb896a2aefeb624cdcf952713c24b"
      url "https://github.com/calvinchengx/entra-emulator/releases/download/v#{version}/entra-emulator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "893a7b817c0c1c4561179ae0fdf93abe4b60cabda8f0602a1324e76227a26df0"
      url "https://github.com/calvinchengx/entra-emulator/releases/download/v#{version}/entra-emulator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "entra-emulator"
  desc "A local, MSAL-compatible emulator of Microsoft Entra ID (Azure AD) in a single Go binary."
  homepage "https://github.com/calvinchengx/entra-emulator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "entra-emulator"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/entra-emulator"]
    end
  end

  # No zap stanza required

end
