# This file was generated by GoReleaser. DO NOT EDIT.
cask "entra-emulator" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "7bb4423227002bd9b28e01125010156435fca6edf44e66656305f265a4fc96d4"
      url "https://github.com/calvinchengx/entra-emulator/releases/download/v#{version}/entra-emulator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "41be228bd331239107e959b5612bec874c8c8d41f5ed89b659e9d3f8ffb021e5"
      url "https://github.com/calvinchengx/entra-emulator/releases/download/v#{version}/entra-emulator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "958d3b14469abc857cd45a1f6efd74e8edc592c62a627b7ee52e1415012061f3"
      url "https://github.com/calvinchengx/entra-emulator/releases/download/v#{version}/entra-emulator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6ea8f920d3f93f7cfe8816fa014bbd97a92bd3c6902147d22d9b640be6f8052f"
      url "https://github.com/calvinchengx/entra-emulator/releases/download/v#{version}/entra-emulator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "entra-emulator"
  desc "A local, MSAL-compatible emulator of Microsoft Entra ID (Azure AD) in a single Go binary."
  homepage "https://github.com/calvinchengx/entra-emulator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "entra-emulator"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/entra-emulator"]
    end
  end

  # No zap stanza required

end
