# This file was generated by GoReleaser. DO NOT EDIT.
cask "entra-emulator" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "82b197c9a184725bafed6c0e80b455a7d44a18397ef1939551582b3fbfa80d7d"
      url "https://github.com/calvinchengx/entra-emulator/releases/download/v#{version}/entra-emulator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "647488bc9287808d3da6929561edda813abd6f0b46e184a4640d3b1da2d39352"
      url "https://github.com/calvinchengx/entra-emulator/releases/download/v#{version}/entra-emulator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "438bc647a8a755ccadc8c4e3fa6e5426a9f3f1df40037fd8c888113776c3a99a"
      url "https://github.com/calvinchengx/entra-emulator/releases/download/v#{version}/entra-emulator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a594869961babdd3fb6eca0dc6d6831b062e56769afc8f03cf871cd388cd7af0"
      url "https://github.com/calvinchengx/entra-emulator/releases/download/v#{version}/entra-emulator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "entra-emulator"
  desc "A local, MSAL-compatible emulator of Microsoft Entra ID (Azure AD) in a single Go binary."
  homepage "https://github.com/calvinchengx/entra-emulator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "entra-emulator"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/entra-emulator"]
    end
  end

  # No zap stanza required

end
