# This file was generated by GoReleaser. DO NOT EDIT.
cask "fabric-emulator" do
  version "0.37.0"

  on_macos do
    on_arm do
      sha256 "6941968bcb5129d6db7e88fc3f17fa98d0e89f0f76cb2534d530d27c2c1e81a0"
      url "https://github.com/calvinchengx/fabric-emulator/releases/download/v#{version}/fabric-emulator_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1c62b3dd4746fb4c0830a3544f66c62fbb0311aea539cb1d4e901ef61d678e29"
      url "https://github.com/calvinchengx/fabric-emulator/releases/download/v#{version}/fabric-emulator_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "586b0288b3843ce41137e0731f0db1168cab64885f4a0dc4cda8c84874e1265f"
      url "https://github.com/calvinchengx/fabric-emulator/releases/download/v#{version}/fabric-emulator_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "898990816a17dca26a012087d48d90fa4e064b1a0471973ad6ad186b2841dd12"
      url "https://github.com/calvinchengx/fabric-emulator/releases/download/v#{version}/fabric-emulator_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fabric-emulator"
  desc "A local emulator of the Microsoft Fabric control plane (workspaces, items, RBAC, git, LRO, OneLake) that validates Entra bearer tokens."
  homepage "https://github.com/calvinchengx/fabric-emulator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fabric-emulator"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fabric-emulator"]
    end
  end

  # No zap stanza required
end
