# This file was generated by GoReleaser. DO NOT EDIT.
cask "fabric-emulator" do
  version "0.31.0"

  on_macos do
    on_intel do
      sha256 "d99d32f78814a639f653bfa621f0204cd32d088c85d0a465acc2b437ae414d71"
      url "https://github.com/calvinchengx/fabric-emulator/releases/download/v#{version}/fabric-emulator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b00905cb6c42ad562a1297b569acf09c971d1d50f32e3647c48b40de46832480"
      url "https://github.com/calvinchengx/fabric-emulator/releases/download/v#{version}/fabric-emulator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "40dcd5337e70a1beae822255f3484a0894d8e22304bc8fb848517126a4f5bff8"
      url "https://github.com/calvinchengx/fabric-emulator/releases/download/v#{version}/fabric-emulator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "352144befe0222986be86eea7602fb7e2dc7b9074ae261df16c89298ff4eac3b"
      url "https://github.com/calvinchengx/fabric-emulator/releases/download/v#{version}/fabric-emulator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fabric-emulator"
  desc "A local emulator of the Microsoft Fabric control plane (workspaces, items, RBAC, git, LRO, OneLake) that validates Entra bearer tokens."
  homepage "https://github.com/calvinchengx/fabric-emulator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fabric-emulator"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fabric-emulator"]
    end
  end

  # No zap stanza required

end
