# This file was generated by GoReleaser. DO NOT EDIT.
cask "fabric-emulator" do
  version "0.13.1"

  on_macos do
    on_intel do
      sha256 "80ed8fce22c8933d5b6f19b52096202ce4800e0472af1e013057aac4b8543d61"
      url "https://github.com/calvinchengx/fabric-emulator/releases/download/v#{version}/fabric-emulator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ae55e5edf06751c9d537bebaac89bb9be086e6a1fa027b21f581ed326e42a2dd"
      url "https://github.com/calvinchengx/fabric-emulator/releases/download/v#{version}/fabric-emulator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a35a4b8add3868ad94689eed012c6ce5a92dcb9d750aebb8e674440e7d43eff4"
      url "https://github.com/calvinchengx/fabric-emulator/releases/download/v#{version}/fabric-emulator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f996d4f626b022a7325a2e52f43842f219a2d6d48d132d486192dbe6f2f6eca"
      url "https://github.com/calvinchengx/fabric-emulator/releases/download/v#{version}/fabric-emulator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fabric-emulator"
  desc "A local emulator of the Microsoft Fabric control plane (workspaces, items, RBAC, git, LRO, OneLake) that validates Entra bearer tokens."
  homepage "https://github.com/calvinchengx/fabric-emulator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fabric-emulator"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fabric-emulator"]
    end
  end

  # No zap stanza required

end
